# Generated by Django 5.2.4 on 2026-08-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_passwordresetotp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                default="2000-01-01", help_text="Used for age-correlated ML analysis"
            ),
            preserve_default=False,
        ),
    ]
