# Generated by Django 6.1 on 2026-08-22 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, help_text="Is account verified"),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.URLField(
                blank=True, help_text="URL to profile image", null=True
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(
                blank=True, help_text="Used for age-correlated ML analysis", null=True
            ),
        ),
    ]
