# Generated by Django 6.1 on 2026-09-09 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_is_verified_user_profile_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='device_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor')], default='doctor', help_text='User role in the system', max_length=20),
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Patient's full name", max_length=255)),
                ('date_of_birth', models.DateField(blank=True, help_text='Used for age-correlated ML analysis', null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='', help_text="Patient's gender", max_length=20)),
                ('device_id', models.CharField(blank=True, help_text="Unique identifier of the patient's wearable device", max_length=100, null=True)),
                ('substance_type', models.CharField(blank=True, choices=[('alcohol', 'Alcohol'), ('opioids', 'Opioids'), ('cannabis', 'Cannabis'), ('stimulants', 'Stimulants'), ('benzodiazepines', 'Benzodiazepines'), ('tobacco', 'Tobacco'), ('polysubstance', 'Polysubstance'), ('other', 'Other')], default='', help_text='Primary substance of concern for relapse monitoring', max_length=30)),
                ('diagnosis_notes', models.TextField(blank=True, default='', help_text='Clinical diagnosis details or relevant medical history')),
                ('notes', models.TextField(blank=True, default='', help_text='General notes about the patient')),
                ('is_active', models.BooleanField(default=True, help_text='Soft-delete flag; inactive patients are hidden from default lists')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctors', models.ManyToManyField(help_text='Doctors managing this patient', related_name='patients', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patients',
                'ordering': ['-created_at'],
            },
        ),
    ]
