# Generated by Django 6.1 on 2026-08-20 07:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DataCollectionDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='The calendar date of data collection (YYYY-MM-DD)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_days', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_collection_days',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.PositiveBigIntegerField(help_text='Unix Epoch timestamp in seconds')),
                ('gsr', models.SmallIntegerField(blank=True, help_text='GSR raw analog value', null=True)),
                ('bodyTemp', models.FloatField(blank=True, help_text='Clinical body temperature in Celsius', null=True)),
                ('hr', models.IntegerField(blank=True, help_text='Heart Rate in bpm', null=True)),
                ('validHR', models.SmallIntegerField(blank=True, help_text='Boolean flag: 1=reliable HR, 0=unreliable', null=True)),
                ('spo2', models.IntegerField(blank=True, help_text='Blood Oxygen Saturation percentage', null=True)),
                ('validSPO2', models.SmallIntegerField(blank=True, help_text='Boolean flag: 1=reliable SpO2, 0=unreliable', null=True)),
                ('bno055_euler_heading', models.FloatField(blank=True, help_text='Euler angle heading (yaw) in degrees', null=True)),
                ('bno055_euler_roll', models.FloatField(blank=True, help_text='Euler angle roll in degrees', null=True)),
                ('bno055_euler_pitch', models.FloatField(blank=True, help_text='Euler angle pitch in degrees', null=True)),
                ('bno055_quat_w', models.FloatField(blank=True, help_text='Quaternion W component', null=True)),
                ('bno055_quat_x', models.FloatField(blank=True, help_text='Quaternion X component', null=True)),
                ('bno055_quat_y', models.FloatField(blank=True, help_text='Quaternion Y component', null=True)),
                ('bno055_quat_z', models.FloatField(blank=True, help_text='Quaternion Z component', null=True)),
                ('bno055_linear_x', models.FloatField(blank=True, help_text='Linear acceleration X excluding gravity', null=True)),
                ('bno055_linear_y', models.FloatField(blank=True, help_text='Linear acceleration Y excluding gravity', null=True)),
                ('bno055_linear_z', models.FloatField(blank=True, help_text='Linear acceleration Z excluding gravity', null=True)),
                ('bno055_gravity_x', models.FloatField(blank=True, help_text='Gravity vector X', null=True)),
                ('bno055_gravity_y', models.FloatField(blank=True, help_text='Gravity vector Y', null=True)),
                ('bno055_gravity_z', models.FloatField(blank=True, help_text='Gravity vector Z', null=True)),
                ('bno055_accel_x', models.FloatField(blank=True, help_text='Raw acceleration X including gravity', null=True)),
                ('bno055_accel_y', models.FloatField(blank=True, help_text='Raw acceleration Y including gravity', null=True)),
                ('bno055_accel_z', models.FloatField(blank=True, help_text='Raw acceleration Z including gravity', null=True)),
                ('bno055_gyro_x', models.FloatField(blank=True, help_text='Angular velocity X', null=True)),
                ('bno055_gyro_y', models.FloatField(blank=True, help_text='Angular velocity Y', null=True)),
                ('bno055_gyro_z', models.FloatField(blank=True, help_text='Angular velocity Z', null=True)),
                ('bno055_mag_x', models.FloatField(blank=True, help_text='Magnetic field X', null=True)),
                ('bno055_mag_y', models.FloatField(blank=True, help_text='Magnetic field Y', null=True)),
                ('bno055_mag_z', models.FloatField(blank=True, help_text='Magnetic field Z', null=True)),
                ('bno055_temp', models.SmallIntegerField(blank=True, help_text='IMU chip temperature in Celsius', null=True)),
                ('bno055_calib_sys', models.SmallIntegerField(blank=True, help_text='System calibration status (0-3)', null=True)),
                ('bno055_calib_gyro', models.SmallIntegerField(blank=True, help_text='Gyroscope calibration status (0-3)', null=True)),
                ('bno055_calib_accel', models.SmallIntegerField(blank=True, help_text='Accelerometer calibration status (0-3)', null=True)),
                ('bno055_calib_mag', models.SmallIntegerField(blank=True, help_text='Magnetometer calibration status (0-3)', null=True)),
                ('synced_at', models.DateTimeField(auto_now_add=True, help_text='Server-side timestamp when this reading was synced')),
                ('collection_day', models.ForeignKey(help_text='The data collection day this reading belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='data.datacollectionday')),
            ],
            options={
                'db_table': 'sensor_readings',
                'ordering': ['-time'],
            },
        ),
        migrations.AddIndex(
            model_name='datacollectionday',
            index=models.Index(fields=['user', 'date'], name='idx_user_date'),
        ),
        migrations.AddConstraint(
            model_name='datacollectionday',
            constraint=models.UniqueConstraint(fields=('user', 'date'), name='unique_user_collection_day'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['collection_day', 'time'], name='idx_collection_day_time'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['time'], name='idx_time'),
        ),
        migrations.AddConstraint(
            model_name='sensorreading',
            constraint=models.UniqueConstraint(fields=('collection_day', 'time'), name='unique_reading_per_day_timestamp'),
        ),
    ]
