# Generated by Django 6.1 on 2026-09-09 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
        ('users', '0005_remove_user_date_of_birth_remove_user_device_id_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='datacollectionday',
            name='unique_user_collection_day',
        ),
        migrations.RemoveIndex(
            model_name='datacollectionday',
            name='idx_user_date',
        ),
        migrations.AddField(
            model_name='datacollectionday',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='collection_days', to='users.patient'),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='datacollectionday',
            index=models.Index(fields=['patient', 'date'], name='idx_patient_date'),
        ),
        migrations.AddConstraint(
            model_name='datacollectionday',
            constraint=models.UniqueConstraint(fields=('patient', 'date'), name='unique_patient_collection_day'),
        ),
        migrations.RemoveField(
            model_name='datacollectionday',
            name='user',
        ),
    ]
