# Generated by Django 6.1 on 2026-08-18 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_readings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['user', 'time'], name='idx_user_time'),
        ),
        migrations.AddIndex(
            model_name='sensorreading',
            index=models.Index(fields=['time'], name='idx_time'),
        ),
        migrations.AddConstraint(
            model_name='sensorreading',
            constraint=models.UniqueConstraint(fields=('user', 'time'), name='unique_user_reading_per_timestamp'),
        ),
    ]
