# Generated by Django 6.1 on 2026-09-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_remove_datacollectionday_unique_user_collection_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datacollectionday',
            name='device_id',
            field=models.CharField(blank=True, help_text='Unique identifier of the wearable device used for this collection day', max_length=100, null=True),
        ),
    ]
